#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <Arduino.h>
#include "Web.h"
#include "LCDLib.h"
#include "SmartPowerStrip.h"
#include "Rele.h"
#include "Band.h"
#include "Menu.h"
#include "EEPROM_Ard.h"
#include "TimeLib.h"
#include "Buttons.h"


String BuildWebPage()
{
	String Page, TmpPage = "";
	short ReleIndx = 0;
	
	Page = "<!DOCTYPE html>";
	Page += "<html>";
	Page += "<head>";
	Page += "<title>Smart Power-Strip</title>";
	Page += "<meta charset=\"UTF-8\">";
	Page += "<script>";		
	for(ReleIndx = RELE_1; ReleIndx < RELE_MAX; ReleIndx++)
	{
		TmpPage += "function SetRele" + String(ReleIndx+1) + "(Status){";
		TmpPage += "var xhttp = new XMLHttpRequest();";
		TmpPage += "xhttp.onreadystatechange = function(){";	
		TmpPage += "if (this.readyState == 4 && this.status == 200){";
		TmpPage += "document.getElementById(\"STATUS_RELE" + String(ReleIndx+1) + "\").innerHTML =";
		TmpPage += "this.responseText;}};";
		TmpPage += "xhttp.open(\"GET\", \"SetRele" + String(ReleIndx+1) + "?STATUS_RELE" + String(ReleIndx+1) + "=\"+Status, true);";
		TmpPage += "xhttp.send();}";
	}	
	Page += TmpPage;
	TmpPage = "";
	Page += "function vuota(){}";				
	Page += "		setInterval(function() 																																											                                                                                                                                          ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		GetTurnOnRele();                                                                                                                                                                                                                                                                                                                          ";
	Page += "		}, 30000); //30s Seconds update rate                                                                                                                                                                                                                                                                                                      ";
	Page += "		                                                                                                                                                                                                                                                                                                                                          ";
	Page += "		function GetTurnOnRele()                                                                                                                                                                                                                                                                                                                  ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		var i;                                                                                                                                                                                                                                                                                                                                    ";
	Page += "		var TurnOnReleId = \"TURN_ON_RELE\";                                                                                                                                                                                                                                                                                                        ";
	Page += "		var TurnOnReleFunc = \"TurnOnRele\";                                                                                                                                                                                                                                                                                                        ";
	Page += "		for (i = 1; i < 9; i++)                                                                                                                                                                                                                                                                                                                   ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "			var xhttp = new XMLHttpRequest();                                                                                                                                                                                                                                                                                                     ";
	Page += "			xhttp.onreadystatechange = function()                                                                                                                                                                                                                                                                                                 ";
	Page += "			{                                                                                                                                                                                                                                                                                                                                     ";
	Page += "			if (this.readyState == 4 && this.status == 200)                                                                                                                                                                                                                                                                                       ";
	Page += "			{                                                                                                                                                                                                                                                                                                                                     ";
	Page += "				document.getElementById(TurnOnReleId+i).innerHTML =                                                                                                                                                                                                                                                                               ";
	Page += "				this.responseText;                                                                                                                                                                                                                                                                                                                ";
	Page += "			}                                                                                                                                                                                                                                                                                                                                     ";
	Page += "			};                                                                                                                                                                                                                                                                                                                                    ";
	Page += "			xhttp.open(\"GET\", TurnOnReleFunc+i, true);                                                                                                                                                                                                                                                                                            ";
	Page += "			xhttp.send();                                                                                                                                                                                                                                                                                                                         ";
	Page += "			setTimeout(vuota, 1000);                                                                                                                                                                                                                                                                                                              ";
	Page += "		}		                                                                                                                                                                                                                                                                                                                                  ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		                                                                                                                                                                                                                                                                                                                                          ";
	Page += "		setInterval(function()                                                                                                                                                                                                                                                                                                                    ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		GetTimerTimeRele();                                                                                                                                                                                                                                                                                                                       ";
	Page += "		}, 60000); // 60s Seconds update rate                                                                                                                                                                                                                                                                                                     ";
	Page += "				                                                                                                                                                                                                                                                                                                                                  ";
	Page += "		function GetTimerTimeRele()                                                                                                                                                                                                                                                                                                               ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		var i;                                                                                                                                                                                                                                                                                                                                    ";
	Page += "		var TimerReleId = \"TIMER_RELE\";                                                                                                                                                                                                                                                                                                           ";
	Page += "		var TimeReleFunc = \"TimerRele\";                                                                                                                                                                                                                                                                                                           ";
	Page += "		for (i = 1; i < 9; i++)                                                                                                                                                                                                                                                                                                                   ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "			var xhttp = new XMLHttpRequest();                                                                                                                                                                                                                                                                                                     ";
	Page += "			xhttp.onreadystatechange = function()                                                                                                                                                                                                                                                                                                 ";
	Page += "			{                                                                                                                                                                                                                                                                                                                                     ";
	Page += "			if (this.readyState == 4 && this.status == 200)                                                                                                                                                                                                                                                                                       ";
	Page += "			{                                                                                                                                                                                                                                                                                                                                     ";
	Page += "				document.getElementById(TimerReleId+i).innerHTML =                                                                                                                                                                                                                                                                                ";
	Page += "				this.responseText;                                                                                                                                                                                                                                                                                                                ";
	Page += "			}                                                                                                                                                                                                                                                                                                                                     ";
	Page += "			};                                                                                                                                                                                                                                                                                                                                    ";
	Page += "			xhttp.open(\"GET\", TimeReleFunc+i, true);                                                                                                                                                                                                                                                                                              ";
	Page += "			xhttp.send();                                                                                                                                                                                                                                                                                                                         ";
	Page += "			setTimeout(vuota, 1000);                                                                                                                                                                                                                                                                                                              ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "	                                                                                                                                                                                                                                                                                                                                              ";
	Page += "	</script>                                                                                                                                                                                                                                                                                                                                     ";
	Page += "	<style>                                                                                                                                                                                                                                                                                                                                       ";
	Page += "	table, th, td                                                                                                                                                                                                                                                                                                                                 ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "			border: 1px solid black;                                                                                                                                                                                                                                                                                                              ";
	Page += "			border-collapse: collapse;                                                                                                                                                                                                                                                                                                            ";
	Page += "			background-color: lavander;                                                                                                                                                                                                                                                                                                           ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		th                                                                                                                                                                                                                                                                                                                                        ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "			height: 50px;                                                                                                                                                                                                                                                                                                                         ";
	Page += "			border-bottom: 1px solid LightGrey;                                                                                                                                                                                                                                                                                                   ";
	Page += "			font-family:\"Verdana\";                                                                                                                                                                                                                                                                                                                ";
	Page += "			font-size:23px;                                                                                                                                                                                                                                                                                                                       ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		td                                                                                                                                                                                                                                                                                                                                        ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "			padding: 10px;                                                                                                                                                                                                                                                                                                                        ";
	Page += "			text-align: center;                                                                                                                                                                                                                                                                                                                   ";
	Page += "			border-bottom: 1px solid LightGrey;                                                                                                                                                                                                                                                                                                   ";
	Page += "			font-size:28px;                                                                                                                                                                                                                                                                                                                       ";
	Page += "			font-family:Verdana;                                                                                                                                                                                                                                                                                                                  ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		tr:hover {background-color:#f5f5f5;}                                                                                                                                                                                                                                                                                                      ";
	Page += "		.button                                                                                                                                                                                                                                                                                                                                   ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "			background-color: #6495ED;                                                                                                                                                                                                                                                                                                            ";
	Page += "			border: black;                                                                                                                                                                                                                                                                                                                        ";
	Page += "			padding: 20px 60px;                                                                                                                                                                                                                                                                                                                   ";
	Page += "			text-align: center;                                                                                                                                                                                                                                                                                                                   ";
	Page += "			text-decoration: none;                                                                                                                                                                                                                                                                                                                ";
	Page += "			display: inline-block;                                                                                                                                                                                                                                                                                                                ";
	Page += "			font-size: 24px;                                                                                                                                                                                                                                                                                                                      ";
	Page += "			margin: 4px 2px;                                                                                                                                                                                                                                                                                                                      ";
	Page += "			cursor: pointer;                                                                                                                                                                                                                                                                                                                      ";
	Page += "			border-radius: 8px;                                                                                                                                                                                                                                                                                                                   ";
	Page += "			box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);                                                                                                                                                                                                                                                              ";
	Page += "			color:white;                                                                                                                                                                                                                                                                                                                          ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		.button:active                                                                                                                                                                                                                                                                                                                            ";
	Page += "		{                                                                                                                                                                                                                                                                                                                                         ";
	Page += "			background-color: #8B0000;                                                                                                                                                                                                                                                                                                            ";
	Page += "			box-shadow: 0 5px #666;                                                                                                                                                                                                                                                                                                               ";
	Page += "			transform: translateY(3px);                                                                                                                                                                                                                                                                                                           ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		h1 {                                                                                                                                                                                                                                                                                                                                      ";
	Page += "			font-size: 60px;                                                                                                                                                                                                                                                                                                                      ";
	Page += "			font-family:\"Verdana\";                                                                                                                                                                                                                                                                                                                ";
	Page += "			color: blue;                                                                                                                                                                                                                                                                                                                          ";
	Page += "			text-align:center;                                                                                                                                                                                                                                                                                                                    ";
	Page += "			text-shadow: 3px 2px red;                                                                                                                                                                                                                                                                                                             ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		h2 {                                                                                                                                                                                                                                                                                                                                      ";
	Page += "			font-size: 45px;                                                                                                                                                                                                                                                                                                                      ";
	Page += "			font-family:\"Verdana\";                                                                                                                                                                                                                                                                                                                ";
	Page += "			color: MediumAquaMarine ;                                                                                                                                                                                                                                                                                                             ";
	Page += "			text-align:center;                                                                                                                                                                                                                                                                                                                    ";
	Page += "			text-decoration: underline;                                                                                                                                                                                                                                                                                                           ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		p {                                                                                                                                                                                                                                                                                                                                       ";
	Page += "			font-size: 13px;                                                                                                                                                                                                                                                                                                                      ";
	Page += "			color: black;                                                                                                                                                                                                                                                                                                                         ";
	Page += "			text-align:center;                                                                                                                                                                                                                                                                                                                    ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "		.small_text {                                                                                                                                                                                                                                                                                                                             ";
	Page += "			font-size: 70%;                                                                                                                                                                                                                                                                                                                       ";
	Page += "			color: #737373;                                                                                                                                                                                                                                                                                                                       ";
	Page += "		}                                                                                                                                                                                                                                                                                                                                         ";
	Page += "	</style>                                                                                                                                                                                                                                                                                                                                      ";
	Page += "	</head>                                                                                                                                                                                                                                                                                                                                       ";
	Page += "	<body style=\"background: linear-gradient(to top, #ffffff 80%, #ccffff 100%);\">                                                                                                                                                                                                                                       ";
	Page += "		<h1>Smart Power-Strip</h1>                                                                                                                                                                                                                                                                                                                ";
	Page += "		<h2>Gestione delle prese e controllo tempi</h2>                                                                                                                                                                                                                                                                                           ";
	Page += "		<table style=\"width:100%;\" border=\"1px solid black;\">                                                                                                                                                                                                                                                                                     ";
	Page += "			<tr style=\"background-color:LightSkyBlue ;\"><th>NOME PRESA</th><th>Accensione / Spegnimento</th><th>Stato Presa</th><th>Tempo Accensione</th><th>Tempo Spegnimento Timer</th></tr>                                       																	                                          ";
	for(ReleIndx = RELE_1; ReleIndx < RELE_MAX; ReleIndx++)
	{
		TmpPage += "<tr><th style=\"background-color:hsl(9, 100%, 80%);\">PRESA " + String(ReleIndx+1) + "</th><td><button class=\"button\" onclick=\"SetRele" + String(ReleIndx+1) + "(1)\">Accesa</button><button class=\"button\" onclick=\"SetRele" + String(ReleIndx+1) + "(0)\">Spenta</button></td><td id=\"STATUS_RELE" + String(ReleIndx+1) + "\" style = \"text-align:center\">SPENTA</td><td id=\"TURN_ON_RELE" + String(ReleIndx+1) + "\">0g 0h 0m</td><td id=\"TIMER_RELE" + String(ReleIndx+1) + "\">0h 0m</td></tr> ";
	}
	Page += TmpPage;
	TmpPage = "";
	Page += "		</table> ";
	Page += "		<p style=\"color:blue; text-align:center; font-family:Verdana; font-size:30px;\">Banda Oraria:</p> <p id=\"BAND_ACTIVE\"> <b style=\"color:MediumSeaGreen;text-align:center; font-family:Verdana; font-size:35px;\">Disattivata</b> </p>    ";
	Page += "		<br>                                                                                                                                                                                                                                  ";
	Page += "		<br>                                                                                                                                                                                                                                  ";
	Page += "		<footer style=\"text-align:center;\">&copy Dario Cavedale</footer>                                                                                                                                                                      ";
	Page += "	</body>                                                                                                                                                                                                                                   ";
	Page += "</html>                                                                                                                                                                                                                                      ";
	return Page;
}